/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdo
 */
public class adminPanel extends javax.swing.JFrame {

    /**
     * Creates new form adminPanel
     */
    public adminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        courseHolder4 = new javax.swing.JTextField();
        timeHolder3 = new javax.swing.JTextField();
        courseHolder2 = new javax.swing.JTextField();
        courseHolder3 = new javax.swing.JTextField();
        courseHolder1 = new javax.swing.JTextField();
        timeHolder4 = new javax.swing.JTextField();
        timeHolder1 = new javax.swing.JTextField();
        timeHolder2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        addQuest = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        editProfileBtn = new javax.swing.JButton();
        editProfileBtn1 = new javax.swing.JButton();
        editProfileBtn2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jDialog3 = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        addressHolder = new javax.swing.JTextField();
        phoneHolder = new javax.swing.JTextField();
        mailHolder = new javax.swing.JTextField();
        nameHolder = new javax.swing.JTextField();
        userNameHolder = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        dobHolder = new javax.swing.JTextField();
        addQuest1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jDialog4 = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        addressHolder1 = new javax.swing.JTextField();
        phoneHolder1 = new javax.swing.JTextField();
        mailHolder1 = new javax.swing.JTextField();
        nameHolder1 = new javax.swing.JTextField();
        doeHolder = new javax.swing.JTextField();
        dobHolder1 = new javax.swing.JTextField();
        addQuest2 = new javax.swing.JButton();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        userNameHolder2 = new javax.swing.JTextField();
        SalaryHolder = new javax.swing.JTextField();
        bioHolder = new javax.swing.JTextField();
        jDialog5 = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        Question2Holder = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jDialog6 = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        addressHolder2 = new javax.swing.JTextField();
        phoneHolder2 = new javax.swing.JTextField();
        mailHolder2 = new javax.swing.JTextField();
        nameHolder2 = new javax.swing.JTextField();
        userNameHolder1 = new javax.swing.JTextField();
        professionHolder = new javax.swing.JTextField();
        addQuest3 = new javax.swing.JButton();
        jPasswordField3 = new javax.swing.JPasswordField();
        jDialog7 = new javax.swing.JDialog();
        jPanel11 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        Question2Holder1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jDialog8 = new javax.swing.JDialog();
        jPanel12 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        userNameFiled1 = new javax.swing.JTextField();
        userNameFiled2 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        submitAnswers = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        userNameFiled = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        addMaterialbtn = new javax.swing.JButton();
        jlable6 = new javax.swing.JLabel();
        nameHolder4 = new javax.swing.JLabel();
        addMaterialbtn1 = new javax.swing.JButton();
        jlable7 = new javax.swing.JLabel();
        addMaterialbtn2 = new javax.swing.JButton();
        jlable8 = new javax.swing.JLabel();
        addMaterialbtn3 = new javax.swing.JButton();
        jlable9 = new javax.swing.JLabel();

        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 209, 205));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/schedule (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel7.setBackground(new java.awt.Color(234, 234, 234));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("x");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 20, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Add Schedule");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, 50));

        jDialog1.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 110));

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(68, 68, 68));
        jLabel6.setText("Time");
        jDialog1.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, -1, 50));

        jComboBox1.setBackground(new java.awt.Color(234, 234, 234));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8" }));
        jComboBox1.setFocusable(false);
        jDialog1.getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 130, 40));

        courseHolder4.setBackground(new java.awt.Color(234, 234, 234));
        courseHolder4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        courseHolder4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        courseHolder4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseHolder4ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(courseHolder4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 440, 50));

        timeHolder3.setBackground(new java.awt.Color(234, 234, 234));
        timeHolder3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        timeHolder3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        timeHolder3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeHolder3ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(timeHolder3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, 230, 50));

        courseHolder2.setBackground(new java.awt.Color(234, 234, 234));
        courseHolder2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        courseHolder2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        courseHolder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseHolder2ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(courseHolder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 440, 50));

        courseHolder3.setBackground(new java.awt.Color(234, 234, 234));
        courseHolder3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        courseHolder3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        courseHolder3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseHolder3ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(courseHolder3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 440, 50));

        courseHolder1.setBackground(new java.awt.Color(234, 234, 234));
        courseHolder1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        courseHolder1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        courseHolder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseHolder1ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(courseHolder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 440, 50));

        timeHolder4.setBackground(new java.awt.Color(234, 234, 234));
        timeHolder4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        timeHolder4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        timeHolder4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeHolder4ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(timeHolder4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 620, 230, 50));

        timeHolder1.setBackground(new java.awt.Color(234, 234, 234));
        timeHolder1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        timeHolder1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        timeHolder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeHolder1ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(timeHolder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 230, 50));

        timeHolder2.setBackground(new java.awt.Color(234, 234, 234));
        timeHolder2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        timeHolder2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        timeHolder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeHolder2ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(timeHolder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 230, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(68, 68, 68));
        jLabel9.setText("select Academic Year: ");
        jDialog1.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(68, 68, 68));
        jLabel10.setText("Course Code");
        jDialog1.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, 50));

        addQuest.setBackground(new java.awt.Color(68, 68, 68));
        addQuest.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        addQuest.setForeground(new java.awt.Color(255, 255, 255));
        addQuest.setText("Add");
        addQuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuestActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(addQuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 740, 90, 50));

        jDialog2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 209, 205));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(234, 234, 234));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("x");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 20, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Manage Students");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 50));

        jDialog2.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 110));

        editProfileBtn.setBackground(new java.awt.Color(68, 68, 68));
        editProfileBtn.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        editProfileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/gears.png"))); // NOI18N
        editProfileBtn.setBorder(null);
        editProfileBtn.setBorderPainted(false);
        editProfileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileBtnActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(editProfileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 150, 150));

        editProfileBtn1.setBackground(new java.awt.Color(68, 68, 68));
        editProfileBtn1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        editProfileBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/delete.png"))); // NOI18N
        editProfileBtn1.setBorder(null);
        editProfileBtn1.setBorderPainted(false);
        editProfileBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editProfileBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileBtn1ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(editProfileBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 150, 150));

        editProfileBtn2.setBackground(new java.awt.Color(68, 68, 68));
        editProfileBtn2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        editProfileBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/plus.png"))); // NOI18N
        editProfileBtn2.setBorder(null);
        editProfileBtn2.setBorderPainted(false);
        editProfileBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editProfileBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileBtn2ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(editProfileBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 150, 150));

        jLabel12.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(68, 68, 68));
        jLabel12.setText("Add Account");
        jDialog2.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, -1, 50));

        jLabel14.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(68, 68, 68));
        jLabel14.setText("Deactivate Account");
        jDialog2.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, 50));

        jLabel15.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(68, 68, 68));
        jLabel15.setText("Add Account");
        jDialog2.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, -1, 50));

        jDialog3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(234, 234, 234));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(68, 68, 68));
        jLabel17.setText("E-mail");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 50));

        jLabel19.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(68, 68, 68));
        jLabel19.setText("Address");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, 50));

        jLabel20.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(68, 68, 68));
        jLabel20.setText("Academic Year");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, 50));

        jLabel23.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(68, 68, 68));
        jLabel23.setText("Phone");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 50));

        jLabel24.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(68, 68, 68));
        jLabel24.setText("Birth Date");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, 50));

        jLabel25.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(68, 68, 68));
        jLabel25.setText("Full Name");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 50));

        jLabel26.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(68, 68, 68));
        jLabel26.setText("UserName");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, 50));

        jLabel27.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(68, 68, 68));
        jLabel27.setText("Password");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, -1, 50));

        addressHolder.setBackground(new java.awt.Color(234, 234, 234));
        addressHolder.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        addressHolder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        addressHolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressHolderActionPerformed(evt);
            }
        });
        jPanel5.add(addressHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 290, 50));

        phoneHolder.setBackground(new java.awt.Color(234, 234, 234));
        phoneHolder.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        phoneHolder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        phoneHolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneHolderActionPerformed(evt);
            }
        });
        jPanel5.add(phoneHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 290, 40));

        mailHolder.setBackground(new java.awt.Color(234, 234, 234));
        mailHolder.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        mailHolder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        mailHolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailHolderActionPerformed(evt);
            }
        });
        jPanel5.add(mailHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 290, 50));

        nameHolder.setBackground(new java.awt.Color(234, 234, 234));
        nameHolder.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        nameHolder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        nameHolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameHolderActionPerformed(evt);
            }
        });
        jPanel5.add(nameHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 290, 50));

        userNameHolder.setBackground(new java.awt.Color(234, 234, 234));
        userNameHolder.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        userNameHolder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        userNameHolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameHolderActionPerformed(evt);
            }
        });
        jPanel5.add(userNameHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 290, 50));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 110, 50));

        dobHolder.setBackground(new java.awt.Color(234, 234, 234));
        dobHolder.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        dobHolder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        dobHolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobHolderActionPerformed(evt);
            }
        });
        jPanel5.add(dobHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 290, 50));

        addQuest1.setBackground(new java.awt.Color(68, 68, 68));
        addQuest1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        addQuest1.setForeground(new java.awt.Color(255, 255, 255));
        addQuest1.setText("Add");
        addQuest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuest1ActionPerformed(evt);
            }
        });
        jPanel5.add(addQuest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 570, 90, 50));

        jPasswordField1.setBackground(new java.awt.Color(234, 234, 234));
        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        jPanel5.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 290, 40));

        jDialog3.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1080, 640));

        jPanel4.setBackground(new java.awt.Color(0, 209, 205));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(234, 234, 234));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("x");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 30, 40));

        jLabel18.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Add new Student");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 50));

        jDialog3.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 110));

        jDialog4.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 209, 205));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Add Teacher");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 50));

        jDialog4.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 110));

        jPanel7.setBackground(new java.awt.Color(234, 234, 234));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(68, 68, 68));
        jLabel21.setText("E-mail");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 50));

        jLabel22.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(68, 68, 68));
        jLabel22.setText("Address");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, 50));

        jLabel28.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(68, 68, 68));
        jLabel28.setText("Bio");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, -1, 50));

        jLabel29.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(68, 68, 68));
        jLabel29.setText("Phone");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 50));

        jLabel30.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(68, 68, 68));
        jLabel30.setText("Birth Date");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, 50));

        jLabel31.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(68, 68, 68));
        jLabel31.setText("Full Name");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 50));

        jLabel32.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(68, 68, 68));
        jLabel32.setText("UserName");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, 50));

        jLabel33.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(68, 68, 68));
        jLabel33.setText("Password");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, -1, 50));

        addressHolder1.setBackground(new java.awt.Color(234, 234, 234));
        addressHolder1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        addressHolder1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        addressHolder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressHolder1ActionPerformed(evt);
            }
        });
        jPanel7.add(addressHolder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 290, 50));

        phoneHolder1.setBackground(new java.awt.Color(234, 234, 234));
        phoneHolder1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        phoneHolder1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        phoneHolder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneHolder1ActionPerformed(evt);
            }
        });
        jPanel7.add(phoneHolder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 290, 40));

        mailHolder1.setBackground(new java.awt.Color(234, 234, 234));
        mailHolder1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        mailHolder1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        mailHolder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailHolder1ActionPerformed(evt);
            }
        });
        jPanel7.add(mailHolder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 290, 50));

        nameHolder1.setBackground(new java.awt.Color(234, 234, 234));
        nameHolder1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        nameHolder1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        nameHolder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameHolder1ActionPerformed(evt);
            }
        });
        jPanel7.add(nameHolder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 290, 50));

        doeHolder.setBackground(new java.awt.Color(234, 234, 234));
        doeHolder.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        doeHolder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        doeHolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doeHolderActionPerformed(evt);
            }
        });
        jPanel7.add(doeHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 290, 50));

        dobHolder1.setBackground(new java.awt.Color(234, 234, 234));
        dobHolder1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        dobHolder1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        dobHolder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobHolder1ActionPerformed(evt);
            }
        });
        jPanel7.add(dobHolder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 290, 50));

        addQuest2.setBackground(new java.awt.Color(68, 68, 68));
        addQuest2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        addQuest2.setForeground(new java.awt.Color(255, 255, 255));
        addQuest2.setText("Add");
        addQuest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuest2ActionPerformed(evt);
            }
        });
        jPanel7.add(addQuest2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 570, 90, 50));

        jPasswordField2.setBackground(new java.awt.Color(234, 234, 234));
        jPasswordField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPasswordField2.setText("jPasswordField1");
        jPasswordField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        jPanel7.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 290, 40));

        jLabel34.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(68, 68, 68));
        jLabel34.setText("Date Of Employement");
        jPanel7.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, 50));

        jLabel35.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(68, 68, 68));
        jLabel35.setText("Salary");
        jPanel7.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, 50));

        userNameHolder2.setBackground(new java.awt.Color(234, 234, 234));
        userNameHolder2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        userNameHolder2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        userNameHolder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameHolder2ActionPerformed(evt);
            }
        });
        jPanel7.add(userNameHolder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 290, 50));

        SalaryHolder.setBackground(new java.awt.Color(234, 234, 234));
        SalaryHolder.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        SalaryHolder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        SalaryHolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryHolderActionPerformed(evt);
            }
        });
        jPanel7.add(SalaryHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 290, 50));

        bioHolder.setBackground(new java.awt.Color(234, 234, 234));
        bioHolder.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        bioHolder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        bioHolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioHolderActionPerformed(evt);
            }
        });
        jPanel7.add(bioHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 290, 50));

        jDialog4.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1080, 640));

        jDialog5.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 209, 205));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Deactivate Student");
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 50));

        jDialog5.getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 110));

        Question2Holder.setBackground(new java.awt.Color(234, 234, 234));
        Question2Holder.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Question2Holder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        Question2Holder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question2HolderActionPerformed(evt);
            }
        });
        jDialog5.getContentPane().add(Question2Holder, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 280, 50));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Deactivate");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDialog5.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 110, 50));

        jDialog6.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(0, 209, 205));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setBackground(new java.awt.Color(234, 234, 234));
        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 0, 0));
        jLabel37.setText("x");
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 30, 40));

        jLabel38.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Add new Parent");
        jPanel9.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 50));

        jDialog6.getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 110));

        jPanel10.setBackground(new java.awt.Color(234, 234, 234));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(68, 68, 68));
        jLabel39.setText("E-mail");
        jPanel10.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 50));

        jLabel40.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(68, 68, 68));
        jLabel40.setText("Address");
        jPanel10.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, 50));

        jLabel42.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(68, 68, 68));
        jLabel42.setText("Phone");
        jPanel10.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 50));

        jLabel43.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(68, 68, 68));
        jLabel43.setText("Profession");
        jPanel10.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, 50));

        jLabel44.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(68, 68, 68));
        jLabel44.setText("Full Name");
        jPanel10.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 50));

        jLabel45.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(68, 68, 68));
        jLabel45.setText("UserName");
        jPanel10.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, 50));

        jLabel46.setFont(new java.awt.Font("Segoe UI Symbol", 0, 23)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(68, 68, 68));
        jLabel46.setText("Password");
        jPanel10.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, -1, 50));

        addressHolder2.setBackground(new java.awt.Color(234, 234, 234));
        addressHolder2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        addressHolder2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        addressHolder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressHolder2ActionPerformed(evt);
            }
        });
        jPanel10.add(addressHolder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 290, 50));

        phoneHolder2.setBackground(new java.awt.Color(234, 234, 234));
        phoneHolder2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        phoneHolder2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        phoneHolder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneHolder2ActionPerformed(evt);
            }
        });
        jPanel10.add(phoneHolder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 290, 40));

        mailHolder2.setBackground(new java.awt.Color(234, 234, 234));
        mailHolder2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        mailHolder2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        mailHolder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailHolder2ActionPerformed(evt);
            }
        });
        jPanel10.add(mailHolder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 290, 50));

        nameHolder2.setBackground(new java.awt.Color(234, 234, 234));
        nameHolder2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        nameHolder2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        nameHolder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameHolder2ActionPerformed(evt);
            }
        });
        jPanel10.add(nameHolder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 290, 50));

        userNameHolder1.setBackground(new java.awt.Color(234, 234, 234));
        userNameHolder1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        userNameHolder1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        userNameHolder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameHolder1ActionPerformed(evt);
            }
        });
        jPanel10.add(userNameHolder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 290, 50));

        professionHolder.setBackground(new java.awt.Color(234, 234, 234));
        professionHolder.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        professionHolder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        professionHolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professionHolderActionPerformed(evt);
            }
        });
        jPanel10.add(professionHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 290, 50));

        addQuest3.setBackground(new java.awt.Color(68, 68, 68));
        addQuest3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        addQuest3.setForeground(new java.awt.Color(255, 255, 255));
        addQuest3.setText("Add");
        addQuest3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuest3ActionPerformed(evt);
            }
        });
        jPanel10.add(addQuest3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 560, 90, 50));

        jPasswordField3.setBackground(new java.awt.Color(234, 234, 234));
        jPasswordField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPasswordField3.setText("jPasswordField1");
        jPasswordField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        jPanel10.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 290, 40));

        jDialog6.getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1080, 620));

        jDialog7.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(0, 209, 205));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Deactivate Teacher");
        jPanel11.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 50));

        jDialog7.getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 110));

        Question2Holder1.setBackground(new java.awt.Color(234, 234, 234));
        Question2Holder1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Question2Holder1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        Question2Holder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question2Holder1ActionPerformed(evt);
            }
        });
        jDialog7.getContentPane().add(Question2Holder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 210, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(68, 68, 68));
        jLabel5.setText("ID");
        jDialog7.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 50));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Deactivate");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jDialog7.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 110, 50));

        jDialog8.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(0, 209, 205));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Assign Teacher To course");
        jPanel12.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 50));

        jDialog8.getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 110));

        jPanel13.setBackground(new java.awt.Color(234, 234, 234));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userNameFiled1.setBackground(new java.awt.Color(234, 234, 234));
        userNameFiled1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        userNameFiled1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        userNameFiled1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFiled1ActionPerformed(evt);
            }
        });
        jPanel13.add(userNameFiled1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 250, -1));

        userNameFiled2.setBackground(new java.awt.Color(234, 234, 234));
        userNameFiled2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        userNameFiled2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        userNameFiled2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFiled2ActionPerformed(evt);
            }
        });
        jPanel13.add(userNameFiled2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 250, -1));

        jLabel48.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(68, 68, 68));
        jLabel48.setText("Course Code:");
        jPanel13.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, 50));

        submitAnswers.setBackground(new java.awt.Color(68, 68, 68));
        submitAnswers.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        submitAnswers.setForeground(new java.awt.Color(255, 255, 255));
        submitAnswers.setText("Assign");
        submitAnswers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAnswersActionPerformed(evt);
            }
        });
        jPanel13.add(submitAnswers, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, 50));

        jLabel47.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(68, 68, 68));
        jLabel47.setText("Teacher ID:");
        jPanel13.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 50));

        jDialog8.getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1040, 570));

        userNameFiled.setBackground(new java.awt.Color(234, 234, 234));
        userNameFiled.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        userNameFiled.setText("User Name");
        userNameFiled.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        userNameFiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFiledActionPerformed(evt);
            }
        });
        jDialog8.getContentPane().add(userNameFiled, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel49.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(68, 68, 68));
        jLabel49.setText("Teacher ID:");
        jDialog8.getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 50));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(68, 68, 68));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/admin.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LogOut");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 550, 110, 50));

        addMaterialbtn.setBackground(new java.awt.Color(78, 78, 78));
        addMaterialbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/classroom.png"))); // NOI18N
        addMaterialbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMaterialbtnMouseClicked(evt);
            }
        });
        addMaterialbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMaterialbtnActionPerformed(evt);
            }
        });
        jPanel2.add(addMaterialbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 150, 160));

        jlable6.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jlable6.setForeground(new java.awt.Color(255, 255, 255));
        jlable6.setText("Assign Teacher to Course");
        jPanel2.add(jlable6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, -1, -1));

        nameHolder4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        nameHolder4.setForeground(new java.awt.Color(255, 255, 255));
        nameHolder4.setText("Abdelrahman");
        jPanel2.add(nameHolder4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        addMaterialbtn1.setBackground(new java.awt.Color(78, 78, 78));
        addMaterialbtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/calendar.png"))); // NOI18N
        addMaterialbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMaterialbtn1MouseClicked(evt);
            }
        });
        addMaterialbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMaterialbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(addMaterialbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 150, 160));

        jlable7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jlable7.setForeground(new java.awt.Color(255, 255, 255));
        jlable7.setText("Add Time Table");
        jPanel2.add(jlable7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        addMaterialbtn2.setBackground(new java.awt.Color(78, 78, 78));
        addMaterialbtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/student (1).png"))); // NOI18N
        addMaterialbtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMaterialbtn2MouseClicked(evt);
            }
        });
        addMaterialbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMaterialbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(addMaterialbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 150, 160));

        jlable8.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jlable8.setForeground(new java.awt.Color(255, 255, 255));
        jlable8.setText("Manage Student");
        jPanel2.add(jlable8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, -1, -1));

        addMaterialbtn3.setBackground(new java.awt.Color(78, 78, 78));
        addMaterialbtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/professor (1).png"))); // NOI18N
        addMaterialbtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMaterialbtn3MouseClicked(evt);
            }
        });
        addMaterialbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMaterialbtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(addMaterialbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 150, 160));

        jlable9.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jlable9.setForeground(new java.awt.Color(255, 255, 255));
        jlable9.setText("Manage Teacher");
        jPanel2.add(jlable9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addMaterialbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMaterialbtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addMaterialbtnMouseClicked

    private void addMaterialbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMaterialbtnActionPerformed
       

    }//GEN-LAST:event_addMaterialbtnActionPerformed

    private void addMaterialbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMaterialbtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addMaterialbtn1MouseClicked

    private void addMaterialbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMaterialbtn1ActionPerformed
        jDialog1.setSize(960, 870);
        jDialog1.show();
    }//GEN-LAST:event_addMaterialbtn1ActionPerformed

    private void addMaterialbtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMaterialbtn2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addMaterialbtn2MouseClicked

    private void addMaterialbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMaterialbtn2ActionPerformed
        jDialog2.setSize(1020, 730);
        jDialog2.show();
    }//GEN-LAST:event_addMaterialbtn2ActionPerformed

    private void addMaterialbtn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMaterialbtn3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addMaterialbtn3MouseClicked

    private void addMaterialbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMaterialbtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMaterialbtn3ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void courseHolder4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseHolder4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseHolder4ActionPerformed

    private void timeHolder3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeHolder3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeHolder3ActionPerformed

    private void courseHolder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseHolder2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseHolder2ActionPerformed

    private void courseHolder3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseHolder3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseHolder3ActionPerformed

    private void courseHolder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseHolder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseHolder1ActionPerformed

    private void timeHolder4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeHolder4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeHolder4ActionPerformed

    private void timeHolder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeHolder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeHolder1ActionPerformed

    private void timeHolder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeHolder2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeHolder2ActionPerformed

    private void addQuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuestActionPerformed
        Component frame = null;
        if("".equals(courseHolder1.getText()) || "".equals(courseHolder2.getText()) || "".equals(courseHolder3.getText()) || "".equals(courseHolder4.getText()) || "".equals(timeHolder1.getText()) || "".equals(timeHolder2.getText())  || "".equals(timeHolder4.getText())) {
             JOptionPane.showMessageDialog(frame,"Please fill or the questions.","Inane error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(frame,"Quiz have ben added");
            jDialog1.setVisible(false);
        }
    }//GEN-LAST:event_addQuestActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void editProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileBtnActionPerformed
        new courseMaterialfrm().setVisible(true);
    }//GEN-LAST:event_editProfileBtnActionPerformed

    private void editProfileBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editProfileBtn1ActionPerformed

    private void editProfileBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileBtn2ActionPerformed
        jDialog3.setSize(1020, 785);
        jDialog3.show();
    }//GEN-LAST:event_editProfileBtn2ActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void addressHolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressHolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressHolderActionPerformed

    private void phoneHolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneHolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneHolderActionPerformed

    private void mailHolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailHolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailHolderActionPerformed

    private void nameHolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameHolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameHolderActionPerformed

    private void userNameHolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameHolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameHolderActionPerformed

    private void dobHolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobHolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobHolderActionPerformed

    private void addQuest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuest1ActionPerformed
      
    }//GEN-LAST:event_addQuest1ActionPerformed

    private void addressHolder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressHolder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressHolder1ActionPerformed

    private void phoneHolder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneHolder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneHolder1ActionPerformed

    private void mailHolder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailHolder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailHolder1ActionPerformed

    private void nameHolder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameHolder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameHolder1ActionPerformed

    private void doeHolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doeHolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doeHolderActionPerformed

    private void dobHolder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobHolder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobHolder1ActionPerformed

    private void addQuest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuest2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addQuest2ActionPerformed

    private void userNameHolder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameHolder2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameHolder2ActionPerformed

    private void SalaryHolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryHolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalaryHolderActionPerformed

    private void bioHolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioHolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bioHolderActionPerformed

    private void Question2HolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question2HolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Question2HolderActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel37MouseClicked

    private void addressHolder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressHolder2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressHolder2ActionPerformed

    private void phoneHolder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneHolder2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneHolder2ActionPerformed

    private void mailHolder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailHolder2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailHolder2ActionPerformed

    private void nameHolder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameHolder2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameHolder2ActionPerformed

    private void userNameHolder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameHolder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameHolder1ActionPerformed

    private void professionHolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professionHolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_professionHolderActionPerformed

    private void addQuest3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuest3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addQuest3ActionPerformed

    private void Question2Holder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question2Holder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Question2Holder1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void userNameFiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameFiledActionPerformed

    private void userNameFiled1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFiled1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameFiled1ActionPerformed

    private void userNameFiled2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFiled2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameFiled2ActionPerformed

    private void submitAnswersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAnswersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitAnswersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Question2Holder;
    private javax.swing.JTextField Question2Holder1;
    private javax.swing.JTextField SalaryHolder;
    private javax.swing.JButton addMaterialbtn;
    private javax.swing.JButton addMaterialbtn1;
    private javax.swing.JButton addMaterialbtn2;
    private javax.swing.JButton addMaterialbtn3;
    private javax.swing.JButton addQuest;
    private javax.swing.JButton addQuest1;
    private javax.swing.JButton addQuest2;
    private javax.swing.JButton addQuest3;
    private javax.swing.JTextField addressHolder;
    private javax.swing.JTextField addressHolder1;
    private javax.swing.JTextField addressHolder2;
    private javax.swing.JTextField bioHolder;
    private javax.swing.JTextField courseHolder1;
    private javax.swing.JTextField courseHolder2;
    private javax.swing.JTextField courseHolder3;
    private javax.swing.JTextField courseHolder4;
    private javax.swing.JTextField dobHolder;
    private javax.swing.JTextField dobHolder1;
    private javax.swing.JTextField doeHolder;
    private javax.swing.JButton editProfileBtn;
    private javax.swing.JButton editProfileBtn1;
    private javax.swing.JButton editProfileBtn2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JDialog jDialog5;
    private javax.swing.JDialog jDialog6;
    private javax.swing.JDialog jDialog7;
    private javax.swing.JDialog jDialog8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JLabel jlable6;
    private javax.swing.JLabel jlable7;
    private javax.swing.JLabel jlable8;
    private javax.swing.JLabel jlable9;
    private javax.swing.JTextField mailHolder;
    private javax.swing.JTextField mailHolder1;
    private javax.swing.JTextField mailHolder2;
    private javax.swing.JTextField nameHolder;
    private javax.swing.JTextField nameHolder1;
    private javax.swing.JTextField nameHolder2;
    private javax.swing.JLabel nameHolder4;
    private javax.swing.JTextField phoneHolder;
    private javax.swing.JTextField phoneHolder1;
    private javax.swing.JTextField phoneHolder2;
    private javax.swing.JTextField professionHolder;
    private javax.swing.JButton submitAnswers;
    private javax.swing.JTextField timeHolder1;
    private javax.swing.JTextField timeHolder2;
    private javax.swing.JTextField timeHolder3;
    private javax.swing.JTextField timeHolder4;
    private javax.swing.JTextField userNameFiled;
    private javax.swing.JTextField userNameFiled1;
    private javax.swing.JTextField userNameFiled2;
    private javax.swing.JTextField userNameHolder;
    private javax.swing.JTextField userNameHolder1;
    private javax.swing.JTextField userNameHolder2;
    // End of variables declaration//GEN-END:variables
}
