/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdo
 */
public class courseMaterialfrm extends javax.swing.JFrame {

    /**
     * Creates new form courseMaterialfrm
     */
    public courseMaterialfrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Question1Holder = new javax.swing.JTextField();
        Question2Holder = new javax.swing.JTextField();
        Question3Holder = new javax.swing.JTextField();
        Question4Holder = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        q1True = new javax.swing.JRadioButton();
        q1False = new javax.swing.JRadioButton();
        q2False = new javax.swing.JRadioButton();
        q2True = new javax.swing.JRadioButton();
        q3True = new javax.swing.JRadioButton();
        q3False = new javax.swing.JRadioButton();
        q4False = new javax.swing.JRadioButton();
        q4True = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        submitAnswers = new javax.swing.JButton();
        q1Group = new javax.swing.ButtonGroup();
        q2Group = new javax.swing.ButtonGroup();
        q3Group = new javax.swing.ButtonGroup();
        q4Group = new javax.swing.ButtonGroup();
        jDialog2 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jDialog3 = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jDialog4 = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        TitleHolder = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        editProfileBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        editProfileBtn1 = new javax.swing.JButton();
        editProfileBtn2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(243, 0, 103));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/test (1).png"))); // NOI18N
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Take Quiz");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, 50));

        jDialog1.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 120));

        Question1Holder.setBackground(new java.awt.Color(234, 234, 234));
        Question1Holder.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Question1Holder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        Question1Holder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question1HolderActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(Question1Holder, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 540, 50));

        Question2Holder.setBackground(new java.awt.Color(234, 234, 234));
        Question2Holder.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Question2Holder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        Question2Holder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question2HolderActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(Question2Holder, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 540, 50));

        Question3Holder.setBackground(new java.awt.Color(234, 234, 234));
        Question3Holder.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Question3Holder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        Question3Holder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question3HolderActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(Question3Holder, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 540, 50));

        Question4Holder.setBackground(new java.awt.Color(234, 234, 234));
        Question4Holder.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Question4Holder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        Question4Holder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question4HolderActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(Question4Holder, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 540, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(68, 68, 68));
        jLabel10.setText("Questions");
        jDialog1.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 140, 70));

        q1True.setBackground(new java.awt.Color(234, 234, 234));
        q1Group.add(q1True);
        q1True.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        q1True.setForeground(new java.awt.Color(68, 68, 68));
        q1True.setText("True");
        q1True.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1TrueActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(q1True, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, -1, -1));

        q1False.setBackground(new java.awt.Color(234, 234, 234));
        q1Group.add(q1False);
        q1False.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        q1False.setForeground(new java.awt.Color(68, 68, 68));
        q1False.setText("False");
        q1False.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1FalseActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(q1False, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 250, -1, -1));

        q2False.setBackground(new java.awt.Color(234, 234, 234));
        q2False.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        q2False.setForeground(new java.awt.Color(68, 68, 68));
        q2False.setText("False");
        q2False.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2FalseActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(q2False, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 340, -1, -1));

        q2True.setBackground(new java.awt.Color(234, 234, 234));
        q2True.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        q2True.setForeground(new java.awt.Color(68, 68, 68));
        q2True.setText("True");
        q2True.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2TrueActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(q2True, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, -1, -1));

        q3True.setBackground(new java.awt.Color(234, 234, 234));
        q3True.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        q3True.setForeground(new java.awt.Color(68, 68, 68));
        q3True.setText("True");
        q3True.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3TrueActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(q3True, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, -1, -1));

        q3False.setBackground(new java.awt.Color(234, 234, 234));
        q3False.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        q3False.setForeground(new java.awt.Color(68, 68, 68));
        q3False.setText("False");
        q3False.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3FalseActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(q3False, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 430, -1, -1));

        q4False.setBackground(new java.awt.Color(234, 234, 234));
        q4False.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        q4False.setForeground(new java.awt.Color(68, 68, 68));
        q4False.setText("False");
        q4False.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4FalseActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(q4False, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 510, -1, -1));

        q4True.setBackground(new java.awt.Color(234, 234, 234));
        q4True.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        q4True.setForeground(new java.awt.Color(68, 68, 68));
        q4True.setText("True");
        q4True.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4TrueActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(q4True, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, -1, -1));

        jPanel3.setBackground(new java.awt.Color(234, 234, 234));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setBackground(new java.awt.Color(68, 68, 68));
        backBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel3.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 100, 50));

        submitAnswers.setBackground(new java.awt.Color(68, 68, 68));
        submitAnswers.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        submitAnswers.setForeground(new java.awt.Color(255, 255, 255));
        submitAnswers.setText("Submit");
        submitAnswers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAnswersActionPerformed(evt);
            }
        });
        jPanel3.add(submitAnswers, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 470, -1, 50));

        jDialog1.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1040, 530));

        jDialog2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(243, 0, 103));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/schedule (1).png"))); // NOI18N
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Quiz List");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, 50));

        jDialog2.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 110));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(60);
        jTable1.setSelectionBackground(new java.awt.Color(243, 0, 103));
        jTable1.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTable1);

        jDialog2.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 990, 400));

        jButton2.setBackground(new java.awt.Color(68, 68, 68));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 590, 90, 50));

        jDialog3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 209, 205));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/book (1).png"))); // NOI18N
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Materials List ");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 50));

        jDialog3.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 120));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setFocusable(false);
        jTable2.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable2.setRowHeight(60);
        jTable2.setSelectionBackground(new java.awt.Color(243, 0, 103));
        jTable2.setShowVerticalLines(false);
        jScrollPane2.setViewportView(jTable2);

        jDialog3.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 990, 400));

        jButton3.setBackground(new java.awt.Color(68, 68, 68));
        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 590, 90, 50));

        jDialog4.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 209, 205));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleHolder.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        TitleHolder.setForeground(new java.awt.Color(255, 255, 255));
        TitleHolder.setText("Title");
        jPanel7.add(TitleHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, 50));

        jDialog4.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 110));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jDialog4.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 800, 710));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 209, 205));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/schedule (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel7.setBackground(new java.awt.Color(234, 234, 234));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("x");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 20, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Maths");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 110));

        jPanel2.setBackground(new java.awt.Color(68, 68, 68));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Assignment");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, -1, 50));

        editProfileBtn.setBackground(new java.awt.Color(68, 68, 68));
        editProfileBtn.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        editProfileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/assign (1).png"))); // NOI18N
        editProfileBtn.setBorder(null);
        editProfileBtn.setBorderPainted(false);
        editProfileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileBtnActionPerformed(evt);
            }
        });
        jPanel2.add(editProfileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 90, 90));

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Material");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, 50));

        editProfileBtn1.setBackground(new java.awt.Color(68, 68, 68));
        editProfileBtn1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        editProfileBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/book (1).png"))); // NOI18N
        editProfileBtn1.setBorder(null);
        editProfileBtn1.setBorderPainted(false);
        editProfileBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editProfileBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileBtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(editProfileBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 90, 90));

        editProfileBtn2.setBackground(new java.awt.Color(68, 68, 68));
        editProfileBtn2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        editProfileBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/answer (1).png"))); // NOI18N
        editProfileBtn2.setBorder(null);
        editProfileBtn2.setBorderPainted(false);
        editProfileBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editProfileBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileBtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(editProfileBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 90, 90));

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quizes");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, 50));

        jButton1.setBackground(new java.awt.Color(68, 68, 68));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 490, 90, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(68, 68, 68));
        jLabel3.setText("Teacher: Youssef Ahmed");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1040, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void editProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileBtnActionPerformed

    }//GEN-LAST:event_editProfileBtnActionPerformed

    private void editProfileBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileBtn1ActionPerformed
           jDialog3.setSize(1070, 695);
           jDialog3.show();
    }//GEN-LAST:event_editProfileBtn1ActionPerformed

    private void editProfileBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileBtn2ActionPerformed
           jDialog2.setSize(1075, 695);
           jDialog2.show();
    }//GEN-LAST:event_editProfileBtn2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new studentPanel().setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void Question1HolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question1HolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Question1HolderActionPerformed

    private void Question2HolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question2HolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Question2HolderActionPerformed

    private void Question3HolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question3HolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Question3HolderActionPerformed

    private void Question4HolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question4HolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Question4HolderActionPerformed

    private void q1TrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1TrueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1TrueActionPerformed

    private void q1FalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1FalseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1FalseActionPerformed

    private void q2FalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2FalseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2FalseActionPerformed

    private void q2TrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2TrueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2TrueActionPerformed

    private void q3TrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3TrueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3TrueActionPerformed

    private void q3FalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3FalseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3FalseActionPerformed

    private void q4FalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4FalseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4FalseActionPerformed

    private void q4TrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4TrueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4TrueActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        jDialog1.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void submitAnswersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAnswersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitAnswersActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jDialog2.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      jDialog3.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Question1Holder;
    private javax.swing.JTextField Question2Holder;
    private javax.swing.JTextField Question3Holder;
    private javax.swing.JTextField Question4Holder;
    private javax.swing.JLabel TitleHolder;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton editProfileBtn;
    private javax.swing.JButton editProfileBtn1;
    private javax.swing.JButton editProfileBtn2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton q1False;
    private javax.swing.ButtonGroup q1Group;
    private javax.swing.JRadioButton q1True;
    private javax.swing.JRadioButton q2False;
    private javax.swing.ButtonGroup q2Group;
    private javax.swing.JRadioButton q2True;
    private javax.swing.JRadioButton q3False;
    private javax.swing.ButtonGroup q3Group;
    private javax.swing.JRadioButton q3True;
    private javax.swing.JRadioButton q4False;
    private javax.swing.ButtonGroup q4Group;
    private javax.swing.JRadioButton q4True;
    private javax.swing.JButton submitAnswers;
    // End of variables declaration//GEN-END:variables
}
