/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdo
 */
public class loginform extends javax.swing.JFrame {

    /**
     * Creates new form loginform
     */
    public loginform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        userRole = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        userNameFiled = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        studentTogle = new javax.swing.JRadioButton();
        TeacherTogle = new javax.swing.JRadioButton();
        AdminTogle = new javax.swing.JRadioButton();
        ParentTogle = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 209, 205));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/school (3).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Central Elementary School");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(76, 76, 76))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 410, 620));

        jPanel2.setBackground(new java.awt.Color(234, 234, 234));

        userNameFiled.setBackground(new java.awt.Color(234, 234, 234));
        userNameFiled.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        userNameFiled.setText("User Name");
        userNameFiled.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        userNameFiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFiledActionPerformed(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(68, 68, 68));
        loginBtn.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(234, 234, 234));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("x");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/user (1).png"))); // NOI18N

        studentTogle.setBackground(new java.awt.Color(234, 234, 234));
        userRole.add(studentTogle);
        studentTogle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        studentTogle.setForeground(new java.awt.Color(68, 68, 68));
        studentTogle.setText("Student");
        studentTogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentTogleActionPerformed(evt);
            }
        });

        TeacherTogle.setBackground(new java.awt.Color(234, 234, 234));
        userRole.add(TeacherTogle);
        TeacherTogle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        TeacherTogle.setForeground(new java.awt.Color(68, 68, 68));
        TeacherTogle.setText("Teacher");
        TeacherTogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherTogleActionPerformed(evt);
            }
        });

        AdminTogle.setBackground(new java.awt.Color(234, 234, 234));
        userRole.add(AdminTogle);
        AdminTogle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        AdminTogle.setForeground(new java.awt.Color(68, 68, 68));
        AdminTogle.setText("Admin");
        AdminTogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminTogleActionPerformed(evt);
            }
        });

        ParentTogle.setBackground(new java.awt.Color(234, 234, 234));
        ParentTogle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ParentTogle.setForeground(new java.awt.Color(68, 68, 68));
        ParentTogle.setText("Parent");
        ParentTogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParentTogleActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/users.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/key.png"))); // NOI18N

        jPasswordField1.setBackground(new java.awt.Color(234, 234, 234));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(253, 253, 253))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ParentTogle)
                        .addGap(18, 18, 18)
                        .addComponent(studentTogle)
                        .addGap(18, 18, 18)
                        .addComponent(TeacherTogle)
                        .addGap(18, 18, 18)
                        .addComponent(AdminTogle)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userNameFiled, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(jPasswordField1))
                        .addGap(168, 168, 168))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userNameFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(64, 64, 64)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentTogle)
                    .addComponent(TeacherTogle)
                    .addComponent(AdminTogle)
                    .addComponent(ParentTogle))
                .addGap(72, 72, 72)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 630, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameFiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameFiledActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void TeacherTogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherTogleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeacherTogleActionPerformed

    private void AdminTogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminTogleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminTogleActionPerformed

    private void ParentTogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParentTogleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ParentTogleActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        if(studentTogle.isSelected()){
            new studentPanel().setVisible(true);
            this.setVisible(false);
        }
        else if(TeacherTogle.isSelected()){
            new teacherPanel().setVisible(true);
            this.setVisible(false);
        }
        else if(AdminTogle.isSelected()){
            new adminPanel().setVisible(true);
            this.setVisible(false);
        }
        else{
             Component frame = null;
             JOptionPane.showMessageDialog(frame,"Please Select your role.","Inane error", JOptionPane.ERROR_MESSAGE);
           
           
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void studentTogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentTogleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentTogleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AdminTogle;
    private javax.swing.JRadioButton ParentTogle;
    private javax.swing.JRadioButton TeacherTogle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JRadioButton studentTogle;
    private javax.swing.JTextField userNameFiled;
    private javax.swing.ButtonGroup userRole;
    // End of variables declaration//GEN-END:variables
}
