/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.JDialog;

/**
 *
 * @author Abdo
 */
public class studentPanel extends javax.swing.JFrame {

    /**
     * Creates new form studentPanel
     */
    public studentPanel() {
        initComponents();
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color (243,0,103));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jlable1 = new javax.swing.JLabel();
        jlable = new javax.swing.JLabel();
        nameHolder3 = new javax.swing.JLabel();
        jlable2 = new javax.swing.JLabel();
        jlable3 = new javax.swing.JLabel();
        timeTableBtn = new javax.swing.JButton();
        editProfileBtn = new javax.swing.JButton();
        jlable4 = new javax.swing.JLabel();
        jlable5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nameHolder = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(68, 68, 68));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/student.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LogOut");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 110, 50));

        jlable1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jlable1.setForeground(new java.awt.Color(255, 255, 255));
        jlable1.setText("ID:");
        jPanel2.add(jlable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jlable.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jlable.setForeground(new java.awt.Color(255, 255, 255));
        jlable.setText("1552");
        jPanel2.add(jlable, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        nameHolder3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        nameHolder3.setForeground(new java.awt.Color(255, 255, 255));
        nameHolder3.setText("Mohamed Ahmed");
        jPanel2.add(nameHolder3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jlable2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jlable2.setForeground(new java.awt.Color(255, 255, 255));
        jlable2.setText("7");
        jPanel2.add(jlable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jlable3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jlable3.setForeground(new java.awt.Color(255, 255, 255));
        jlable3.setText("Edit Profile");
        jPanel2.add(jlable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        timeTableBtn.setBackground(new java.awt.Color(68, 68, 68));
        timeTableBtn.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        timeTableBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/schedule.png"))); // NOI18N
        timeTableBtn.setBorder(null);
        timeTableBtn.setBorderPainted(false);
        timeTableBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        timeTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeTableBtnActionPerformed(evt);
            }
        });
        jPanel2.add(timeTableBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 40, 40));

        editProfileBtn.setBackground(new java.awt.Color(68, 68, 68));
        editProfileBtn.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        editProfileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/resume.png"))); // NOI18N
        editProfileBtn.setBorder(null);
        editProfileBtn.setBorderPainted(false);
        editProfileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileBtnActionPerformed(evt);
            }
        });
        jPanel2.add(editProfileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 433, 40, 40));

        jlable4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jlable4.setForeground(new java.awt.Color(255, 255, 255));
        jlable4.setText("Grade:");
        jPanel2.add(jlable4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jlable5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jlable5.setForeground(new java.awt.Color(255, 255, 255));
        jlable5.setText("Time Table");
        jPanel2.add(jlable5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 620));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameHolder.setBackground(new java.awt.Color(234, 234, 234));
        nameHolder.setFont(new java.awt.Font("Segoe UI Symbol", 1, 48)); // NOI18N
        nameHolder.setForeground(new java.awt.Color(68, 68, 68));
        nameHolder.setText("Course List");
        jPanel1.add(nameHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(60);
        jTable1.setSelectionBackground(new java.awt.Color(243, 0, 103));
        jTable1.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 640, 410));

        jLabel2.setBackground(new java.awt.Color(234, 234, 234));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("x");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 700, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void timeTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeTableBtnActionPerformed
        new timeTable().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_timeTableBtnActionPerformed

    private void editProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileBtnActionPerformed
       new courseMaterialfrm().setVisible(true);
    }//GEN-LAST:event_editProfileBtnActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editProfileBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlable;
    private javax.swing.JLabel jlable1;
    private javax.swing.JLabel jlable2;
    private javax.swing.JLabel jlable3;
    private javax.swing.JLabel jlable4;
    private javax.swing.JLabel jlable5;
    private javax.swing.JLabel nameHolder;
    private javax.swing.JLabel nameHolder3;
    private javax.swing.JButton timeTableBtn;
    // End of variables declaration//GEN-END:variables
}
