/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdo
 */
public class teacherPanel extends javax.swing.JFrame {

    /**
     * Creates new form teacherPanel
     */
    public teacherPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        titleFiled = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        addQuest1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jDialog2 = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Question4Holder = new javax.swing.JTextField();
        Question3Holder = new javax.swing.JTextField();
        Question2Holder = new javax.swing.JTextField();
        Question1Holder = new javax.swing.JTextField();
        addQuest = new javax.swing.JButton();
        q4True = new javax.swing.JRadioButton();
        q3False = new javax.swing.JRadioButton();
        q1False = new javax.swing.JRadioButton();
        q2False = new javax.swing.JRadioButton();
        q4False = new javax.swing.JRadioButton();
        q1True = new javax.swing.JRadioButton();
        q3True = new javax.swing.JRadioButton();
        q2True = new javax.swing.JRadioButton();
        backBtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        q1group = new javax.swing.ButtonGroup();
        q2group = new javax.swing.ButtonGroup();
        q3group = new javax.swing.ButtonGroup();
        q4group = new javax.swing.ButtonGroup();
        jDialog3 = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        GradeD = new javax.swing.JRadioButton();
        GradeC = new javax.swing.JRadioButton();
        GradeF = new javax.swing.JRadioButton();
        GradeA = new javax.swing.JRadioButton();
        GradeB = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        addGrade = new javax.swing.JButton();
        Grade_btn_group = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jlable1 = new javax.swing.JLabel();
        jlable = new javax.swing.JLabel();
        ass_Gradebtn = new javax.swing.JButton();
        jlable5 = new javax.swing.JLabel();
        addMaterialbtn = new javax.swing.JButton();
        addQuizBtn = new javax.swing.JButton();
        jlable6 = new javax.swing.JLabel();
        jlable7 = new javax.swing.JLabel();
        nameHolder4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameHolder3 = new javax.swing.JLabel();
        nameHolder5 = new javax.swing.JLabel();
        nameHolder6 = new javax.swing.JLabel();
        nameHolder7 = new javax.swing.JLabel();
        nameHolder8 = new javax.swing.JLabel();

        jDialog1.setMaximumSize(new java.awt.Dimension(500, 300));
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(243, 0, 103));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/organize.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Manage Material");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 220, 50));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 120));

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(68, 68, 68));
        jLabel3.setText("Maths");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 220, 50));

        titleFiled.setBackground(new java.awt.Color(234, 234, 234));
        titleFiled.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        titleFiled.setText("Title");
        titleFiled.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        titleFiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleFiledActionPerformed(evt);
            }
        });
        jPanel3.add(titleFiled, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 300, 40));

        jTextArea1.setBackground(new java.awt.Color(234, 234, 234));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setName(""); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 700, 250));

        jButton2.setBackground(new java.awt.Color(68, 68, 68));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 90, 50));

        addQuest1.setBackground(new java.awt.Color(68, 68, 68));
        addQuest1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        addQuest1.setForeground(new java.awt.Color(255, 255, 255));
        addQuest1.setText("Add");
        addQuest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuest1ActionPerformed(evt);
            }
        });
        jPanel3.add(addQuest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 550, 90, 50));

        jPanel6.setBackground(new java.awt.Color(234, 234, 234));
        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 940, 520));

        jDialog1.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 620));

        jDialog2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 209, 205));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/test (1).png"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Add new Quiz");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, 50));

        jDialog2.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 120));

        Question4Holder.setBackground(new java.awt.Color(234, 234, 234));
        Question4Holder.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Question4Holder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        Question4Holder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question4HolderActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(Question4Holder, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 540, 50));

        Question3Holder.setBackground(new java.awt.Color(234, 234, 234));
        Question3Holder.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Question3Holder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        Question3Holder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question3HolderActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(Question3Holder, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 540, 50));

        Question2Holder.setBackground(new java.awt.Color(234, 234, 234));
        Question2Holder.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Question2Holder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        Question2Holder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question2HolderActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(Question2Holder, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 540, 50));

        Question1Holder.setBackground(new java.awt.Color(234, 234, 234));
        Question1Holder.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Question1Holder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(243, 0, 103)));
        Question1Holder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question1HolderActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(Question1Holder, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 540, 50));

        addQuest.setBackground(new java.awt.Color(68, 68, 68));
        addQuest.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        addQuest.setForeground(new java.awt.Color(255, 255, 255));
        addQuest.setText("Add");
        addQuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuestActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(addQuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 580, 90, 50));

        q4True.setBackground(new java.awt.Color(234, 234, 234));
        q4group.add(q4True);
        q4True.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        q4True.setForeground(new java.awt.Color(68, 68, 68));
        q4True.setText("True");
        q4True.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4TrueActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(q4True, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, -1, -1));

        q3False.setBackground(new java.awt.Color(234, 234, 234));
        q3group.add(q3False);
        q3False.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        q3False.setForeground(new java.awt.Color(68, 68, 68));
        q3False.setText("False");
        q3False.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3FalseActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(q3False, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 390, -1, -1));

        q1False.setBackground(new java.awt.Color(234, 234, 234));
        q1group.add(q1False);
        q1False.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        q1False.setForeground(new java.awt.Color(68, 68, 68));
        q1False.setText("False");
        q1False.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1FalseActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(q1False, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 210, -1, -1));

        q2False.setBackground(new java.awt.Color(234, 234, 234));
        q2group.add(q2False);
        q2False.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        q2False.setForeground(new java.awt.Color(68, 68, 68));
        q2False.setText("False");
        q2False.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2FalseActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(q2False, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 300, -1, -1));

        q4False.setBackground(new java.awt.Color(234, 234, 234));
        q4group.add(q4False);
        q4False.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        q4False.setForeground(new java.awt.Color(68, 68, 68));
        q4False.setText("False");
        q4False.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4FalseActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(q4False, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, -1, -1));

        q1True.setBackground(new java.awt.Color(234, 234, 234));
        q1group.add(q1True);
        q1True.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        q1True.setForeground(new java.awt.Color(68, 68, 68));
        q1True.setText("True");
        q1True.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1TrueActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(q1True, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, -1, -1));

        q3True.setBackground(new java.awt.Color(234, 234, 234));
        q3group.add(q3True);
        q3True.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        q3True.setForeground(new java.awt.Color(68, 68, 68));
        q3True.setText("True");
        q3True.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3TrueActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(q3True, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, -1, -1));

        q2True.setBackground(new java.awt.Color(234, 234, 234));
        q2group.add(q2True);
        q2True.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        q2True.setForeground(new java.awt.Color(68, 68, 68));
        q2True.setText("True");
        q2True.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2TrueActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(q2True, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, -1, -1));

        backBtn.setBackground(new java.awt.Color(68, 68, 68));
        backBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 90, 50));

        jPanel7.setBackground(new java.awt.Color(234, 234, 234));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(68, 68, 68));
        jLabel7.setText("Questions");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, 50));

        jDialog2.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1030, 710));

        jDialog3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(243, 0, 103));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/exam (1).png"))); // NOI18N
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Assign Grades");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 50));

        jDialog3.getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 140));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(40);
        jTable1.setSelectionBackground(new java.awt.Color(243, 0, 103));
        jTable1.setShowVerticalLines(false);
        jScrollPane2.setViewportView(jTable1);

        jDialog3.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 960, 330));

        Grade_btn_group.add(GradeD);
        GradeD.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        GradeD.setText("D");
        GradeD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeDActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(GradeD, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, -1, -1));

        Grade_btn_group.add(GradeC);
        GradeC.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        GradeC.setText("C");
        GradeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeCActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(GradeC, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, -1, -1));

        Grade_btn_group.add(GradeF);
        GradeF.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        GradeF.setText("F");
        GradeF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeFActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(GradeF, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 540, -1, -1));

        Grade_btn_group.add(GradeA);
        GradeA.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        GradeA.setText("A");
        GradeA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeAActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(GradeA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, -1, -1));

        Grade_btn_group.add(GradeB);
        GradeB.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        GradeB.setText("B");
        GradeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeBActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(GradeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, -1, -1));

        jButton3.setBackground(new java.awt.Color(68, 68, 68));
        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 100, 50));

        addGrade.setBackground(new java.awt.Color(68, 68, 68));
        addGrade.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        addGrade.setForeground(new java.awt.Color(255, 255, 255));
        addGrade.setText("Add");
        addGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGradeActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(addGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 630, 110, 50));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(68, 68, 68));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/teacher (1).png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LogOut");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, 110, 50));

        jlable1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jlable1.setForeground(new java.awt.Color(255, 255, 255));
        jlable1.setText("ID:");
        jPanel2.add(jlable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jlable.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jlable.setForeground(new java.awt.Color(255, 255, 255));
        jlable.setText("1552");
        jPanel2.add(jlable, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        ass_Gradebtn.setBackground(new java.awt.Color(68, 68, 68));
        ass_Gradebtn.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        ass_Gradebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/exam.png"))); // NOI18N
        ass_Gradebtn.setBorder(null);
        ass_Gradebtn.setBorderPainted(false);
        ass_Gradebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ass_Gradebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ass_GradebtnActionPerformed(evt);
            }
        });
        jPanel2.add(ass_Gradebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 363, 50, 40));

        jlable5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jlable5.setForeground(new java.awt.Color(255, 255, 255));
        jlable5.setText("Add Quiz");
        jPanel2.add(jlable5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        addMaterialbtn.setBackground(new java.awt.Color(68, 68, 68));
        addMaterialbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/studying.png"))); // NOI18N
        addMaterialbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMaterialbtnMouseClicked(evt);
            }
        });
        addMaterialbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMaterialbtnActionPerformed(evt);
            }
        });
        jPanel2.add(addMaterialbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 50, 40));

        addQuizBtn.setBackground(new java.awt.Color(68, 68, 68));
        addQuizBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/questionnaire (1).png"))); // NOI18N
        addQuizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuizBtnActionPerformed(evt);
            }
        });
        jPanel2.add(addQuizBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 50, 40));

        jlable6.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jlable6.setForeground(new java.awt.Color(255, 255, 255));
        jlable6.setText("Add Material");
        jPanel2.add(jlable6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        jlable7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jlable7.setForeground(new java.awt.Color(255, 255, 255));
        jlable7.setText("Assign grade");
        jPanel2.add(jlable7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        nameHolder4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 26)); // NOI18N
        nameHolder4.setForeground(new java.awt.Color(255, 255, 255));
        nameHolder4.setText("Mohamed Ahmed");
        jPanel2.add(nameHolder4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 620));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(234, 234, 234));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("x");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, -1, -1));

        nameHolder3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        nameHolder3.setForeground(new java.awt.Color(68, 68, 68));
        nameHolder3.setText("Monday 1pm");
        jPanel1.add(nameHolder3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        nameHolder5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 48)); // NOI18N
        nameHolder5.setForeground(new java.awt.Color(0, 209, 205));
        nameHolder5.setText("Math Teacher");
        jPanel1.add(nameHolder5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        nameHolder6.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        nameHolder6.setForeground(new java.awt.Color(68, 68, 68));
        nameHolder6.setText("Grade 7");
        jPanel1.add(nameHolder6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        nameHolder7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        nameHolder7.setForeground(new java.awt.Color(68, 68, 68));
        nameHolder7.setText("Course Time:");
        jPanel1.add(nameHolder7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        nameHolder8.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        nameHolder8.setForeground(new java.awt.Color(68, 68, 68));
        nameHolder8.setText("Academic Year: ");
        jPanel1.add(nameHolder8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 700, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ass_GradebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ass_GradebtnActionPerformed
        jDialog3.setSize(1130, 735);
        this.setVisible(false);
        jDialog3.show();
    }//GEN-LAST:event_ass_GradebtnActionPerformed

    private void addMaterialbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMaterialbtnActionPerformed
        jDialog1.setSize(955, 663);
        jDialog1.show();
    
      
        
    }//GEN-LAST:event_addMaterialbtnActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void titleFiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleFiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleFiledActionPerformed

    private void addMaterialbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMaterialbtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addMaterialbtnMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jDialog1.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void Question4HolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question4HolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Question4HolderActionPerformed

    private void Question3HolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question3HolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Question3HolderActionPerformed

    private void Question2HolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question2HolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Question2HolderActionPerformed

    private void Question1HolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question1HolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Question1HolderActionPerformed

    private void addQuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuestActionPerformed
        Component frame = null;
        if("".equals(Question1Holder.getText()) || "".equals(Question2Holder.getText()) || "".equals(Question3Holder.getText()) || "".equals(Question4Holder.getText())) {
            JOptionPane.showMessageDialog(frame,"Please fill or the questions.","Inane error", JOptionPane.ERROR_MESSAGE);
        }
          else{
             JOptionPane.showMessageDialog(frame,"Quiz have ben added");
             jDialog1.setVisible(false);
         }
    }//GEN-LAST:event_addQuestActionPerformed

    private void q3FalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3FalseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3FalseActionPerformed

    private void q4TrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4TrueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4TrueActionPerformed

    private void q1FalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1FalseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1FalseActionPerformed

    private void q2FalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2FalseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2FalseActionPerformed

    private void q4FalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4FalseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4FalseActionPerformed

    private void q1TrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1TrueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1TrueActionPerformed

    private void q2TrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2TrueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2TrueActionPerformed

    private void q3TrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3TrueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3TrueActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
       jDialog2.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void addQuizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuizBtnActionPerformed
        jDialog2.setBackground(new Color(240,240,240)); 
        jDialog2.setSize(1039, 695);
        jDialog2.show();
    }//GEN-LAST:event_addQuizBtnActionPerformed

    private void addQuest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuest1ActionPerformed
         Component frame = null;
         
         if("".equals(titleFiled.getText()) || "".equals(jTextArea1.getText())){
             
             JOptionPane.showMessageDialog(frame,"Title or content are empty.","Inane error", JOptionPane.ERROR_MESSAGE);
         }
         else{
             JOptionPane.showMessageDialog(frame,"Material have ben added");
             jDialog1.setVisible(false);
         }
    }//GEN-LAST:event_addQuest1ActionPerformed

    private void GradeDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeDActionPerformed

    private void GradeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeCActionPerformed

    private void GradeAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeAActionPerformed

    private void GradeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeBActionPerformed

    private void GradeFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeFActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       jDialog3.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void addGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addGradeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacherPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacherPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacherPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacherPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton GradeA;
    private javax.swing.JRadioButton GradeB;
    private javax.swing.JRadioButton GradeC;
    private javax.swing.JRadioButton GradeD;
    private javax.swing.JRadioButton GradeF;
    private javax.swing.ButtonGroup Grade_btn_group;
    private javax.swing.JTextField Question1Holder;
    private javax.swing.JTextField Question2Holder;
    private javax.swing.JTextField Question3Holder;
    private javax.swing.JTextField Question4Holder;
    private javax.swing.JButton addGrade;
    private javax.swing.JButton addMaterialbtn;
    private javax.swing.JButton addQuest;
    private javax.swing.JButton addQuest1;
    private javax.swing.JButton addQuizBtn;
    private javax.swing.JButton ass_Gradebtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jlable;
    private javax.swing.JLabel jlable1;
    private javax.swing.JLabel jlable5;
    private javax.swing.JLabel jlable6;
    private javax.swing.JLabel jlable7;
    private javax.swing.JLabel nameHolder3;
    private javax.swing.JLabel nameHolder4;
    private javax.swing.JLabel nameHolder5;
    private javax.swing.JLabel nameHolder6;
    private javax.swing.JLabel nameHolder7;
    private javax.swing.JLabel nameHolder8;
    private javax.swing.JRadioButton q1False;
    private javax.swing.JRadioButton q1True;
    private javax.swing.ButtonGroup q1group;
    private javax.swing.JRadioButton q2False;
    private javax.swing.JRadioButton q2True;
    private javax.swing.ButtonGroup q2group;
    private javax.swing.JRadioButton q3False;
    private javax.swing.JRadioButton q3True;
    private javax.swing.ButtonGroup q3group;
    private javax.swing.JRadioButton q4False;
    private javax.swing.JRadioButton q4True;
    private javax.swing.ButtonGroup q4group;
    private javax.swing.JTextField titleFiled;
    // End of variables declaration//GEN-END:variables


}
